[package]
name = "emeraldian"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "emeraldian"

[dependencies]
otui-core.workspace = true
otui-theme.workspace = true
otui-agent.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
image.workspace = true
crossterm.workspace = true
serde.workspace = true
toml.workspace = true
dirs.workspace = true
anyhow.workspace = true
unicode-width.workspace = true
serde_json.workspace = true

[dev-dependencies]
lz-str.workspace = true
otui-core = { workspace = true, features = ["test-support"] }
